{% set name = "bely-api" %}
{% set version = "2026.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../packages/api

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python>=3.10
    - hatchling
    - pip
  run:
    - python
    - python-dateutil
    - pydantic
    - urllib3
    - certifi

test:
  imports:
    - BelyApiFactory

about:
  home: "https://github.com/AdvancedPhotonSource/BELY"
  license: "Copyright (c) UChicago Argonne, LLC. All rights reserved."
  summary: "Python client API library used to communicate with BELY API."
