/*
 * Copyright (c) UChicago Argonne, LLC. All rights reserved.
 * See LICENSE file.
 */
package gov.anl.aps.logr.portal.view.objects;

import gov.anl.aps.logr.portal.model.db.entities.Log;
import gov.anl.aps.logr.portal.model.db.entities.LogReaction;
import gov.anl.aps.logr.portal.model.db.entities.Reaction;
import gov.anl.aps.logr.portal.model.db.entities.UserInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * Wrapper for the log reactions that allows for grouping and simplifies the view. 
 * 
 * @author djarosz
 */
public class GroupedReaction {
    
    List<LogReaction> logReactioList; 
    Reaction reaction; 
    
    private Boolean userReaction; 

    public GroupedReaction(List<LogReaction> logReactioList, Reaction reaction, Boolean userReaction) {
        this.logReactioList = logReactioList;
        this.reaction = reaction;
        this.userReaction = userReaction;
    }   
    
    public static List<GroupedReaction> createGroupedReactionList(List<Reaction> reactionList, Log log, UserInfo user) {
        List<GroupedReaction> groupedReactions = new ArrayList<>(); 
        
        List<LogReaction> logReactionList = log.getLogReactionList();
        
        
        for (Reaction reaction: reactionList) {            
            boolean userReaction = false; 
            List<LogReaction> matchedLogReactions = new ArrayList<>();             
            
            for (LogReaction logReaction : logReactionList) {
                Reaction itrRec = logReaction.getReaction();
                
                if (itrRec.equals(reaction)) { 
                    UserInfo userId = logReaction.getUserInfo();
                    if (userId.equals(user)) {
                        userReaction = true; 
                    }
                    matchedLogReactions.add(logReaction); 
                }
            }           
            
            GroupedReaction gr = new GroupedReaction(matchedLogReactions, reaction, userReaction); 
            groupedReactions.add(gr);
        }
        
        return groupedReactions;         
    }        

    public List<LogReaction> getLogReactionList() {
        return logReactioList;
    }

    public Reaction getReaction() {
        return reaction;
    }
    
    public Integer getReactionCount() {
        return logReactioList.size(); 
    }

    public boolean isUserReaction() {
        return userReaction;
    }

    public void setUserReaction(boolean userReaction) {
        // Set method required to satisfy p:selectBooleanButton widget. 
        // Should be autogenerated.
    }
    
}
