resourcePackages:
- gov.anl.aps.logr.rest
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '2024.5'
    title: BELY API
    description: 'The API that provides access to BELY data.'
    contact:
      email: djarosz@anl.gov
    license:
      name: Copyright (c) UChicago Argonne, LLC. All rights reserved.
