#! /bin/sh
### BEGIN INIT INFO
# Provides:          glassfish
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Controls CDB GlassFish application server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Set root to default if needed.
MY_DIR=`dirname $0` && cd $MY_DIR && MY_DIR=`pwd`
if [ -z "${LOGR_ROOT_DIR}" ]; then
    LOGR_ROOT_DIR=$MY_DIR/../..
fi
        
# Source environment file.
LOGR_USER=`id -nu`
LOGR_HOST=`hostname -s`
LOGR_ENV_FILE=${LOGR_ROOT_DIR}/setup.sh
if [ ! -f ${LOGR_ENV_FILE} ]; then
    echo "Environment file ${LOGR_ENV_FILE} does not exist." 
    exit 2
fi
. ${LOGR_ENV_FILE} > /dev/null

export AS_JAVA=$LOGR_SUPPORT_DIR/java/$LOGR_HOST_ARCH
GLASSFISH_DIR=$LOGR_SUPPORT_DIR/payara/$LOGR_HOST_ARCH
DERBY_DIR=$LOGR_SUPPORT_DIR/payara/$LOGR_HOST_ARCH/javadb/bin

LOGR_DAEMON_NAME=glassfish
LOGR_DAEMON_CONTROL_CMD=$GLASSFISH_DIR/bin/asadmin
LOGR_DOMAIN_NAME=production
LOGR_DAEMON_START_ARGS="start-domain $LOGR_DOMAIN_NAME"
LOGR_DAEMON_STOP_ARGS="stop-domain $LOGR_DOMAIN_NAME"
LOGR_DAEMON_STATUS_CMDS="uptime list-domains list-applications list-jdbc-resources"

start() {
    echo -n $"Starting ${LOGR_DAEMON_NAME}: "       
    # Check if we're a privileged user
    if [ `id -u` = 0 -a ${LOGR_USER} != "root" ]; then
        su -m -c "${LOGR_DAEMON_CONTROL_CMD} ${LOGR_DAEMON_START_ARGS}" ${LOGR_USER}
    else
        ${LOGR_DAEMON_CONTROL_CMD} ${LOGR_DAEMON_START_ARGS}
    fi
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success $"${LOGR_DAEMON_NAME} startup" || failure $"${LOGR_DAEMON_NAME} startup"
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping ${LOGR_DAEMON_NAME}: "       
    # Check if we're a privileged user
    if [ `id -u` = 0 -a ${LOGR_USER} != "root" ]; then
        su -m -c "${LOGR_DAEMON_CONTROL_CMD} ${LOGR_DAEMON_STOP_ARGS}" ${LOGR_USER}
    else
        ${LOGR_DAEMON_CONTROL_CMD} ${LOGR_DAEMON_STOP_ARGS}
    fi
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success $"${LOGR_DAEMON_NAME} shutdown" || failure $"${LOGR_DAEMON_NAME} shutdown"
    echo
    return $RETVAL
}

status() {
    # Check if we're a privileged user
    if [ `id -u` = 0 -a ${LOGR_USER} != "root" ]; then
        for cmd in ${LOGR_DAEMON_STATUS_CMDS}; do
            su -m -c "${LOGR_DAEMON_CONTROL_CMD} ${cmd}" ${LOGR_USER}
        done
    else
        for cmd in ${LOGR_DAEMON_STATUS_CMDS}; do
            ${LOGR_DAEMON_CONTROL_CMD} ${cmd}
        done
    fi
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    status)
        status
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
esac


