#!/home/phoebus/ECHANDLER/sandbox/hla/bely-client/conda/bin/python

import click

from commands import (
    cmd_new_doc,
    cmd_list_docs,
    cmd_update_entry,
    cmd_add_entry,
    cmd_list_types,
    cmd_list_systems,
    cmd_list_templates,
    cmd_show_config,
    cmd_edit_config,
)


CONTEXT_SETTINGS = dict(help_option_names=["-h", "--help"])


@click.group(context_settings=CONTEXT_SETTINGS)
def cli():
    """BELY logbook CLI"""
    pass


# -- doc --

@cli.group("doc")
def doc_group():
    """Log document commands."""
    pass


@doc_group.command("new")
@click.option("--type", "type_", required=True, help="Logbook type (e.g. ops, controls)")
@click.option("--name", required=True, help="Name for the new document")
@click.option("--file", "file", default=None, help="Markdown file for the first log entry")
@click.option("--template", default=None, help="Template name to use")
@click.option("--systems", default=None, help="Comma-separated system list (e.g. SR,software)")
@click.option("--no-template", is_flag=True, help="Skip template selection")
@click.option("--no-prompt", is_flag=True, help="Non-interactive mode (no prompts)")
def doc_new(**kwargs):
    """Create a new log document."""
    cmd_new_doc(**kwargs)


@doc_group.command("list")
@click.option("--limit", default=20, type=int, help="Max documents to return (default 20)")
def doc_list(**kwargs):
    """List recent log documents created by you."""
    cmd_list_docs(**kwargs)


# -- entry --

@cli.group("entry")
def entry_group():
    """Log entry commands."""
    pass


@entry_group.command("add")
@click.option("--name", required=True, help="Log document name")
@click.option("--file", "file", default=None, help="Markdown file with entry content")
@click.option("--text", default=None, help="Inline text for the entry")
@click.option("--add-attachment", default=None, help="File to attach to the entry")
def entry_add(**kwargs):
    """Add a new log entry to an existing document."""
    cmd_add_entry(**kwargs)


@entry_group.command("update")
@click.option("--name", default=None, help="Log document name")
@click.option("--entry-id", default=None, type=int, help="Specific log entry ID to update")
@click.option("--file", "file", default=None, help="Markdown file with updated content")
@click.option("--text", default=None, help="Inline text for the entry")
@click.option("--add-attachment", default=None, help="File to attach to the entry")
def entry_update(**kwargs):
    """Update an existing log entry."""
    cmd_update_entry(**kwargs)


# -- type --

@cli.group("type")
def type_group():
    """Logbook type commands."""
    pass


@type_group.command("list")
def type_list():
    """List available logbook types."""
    cmd_list_types()


# -- system --

@cli.group("system")
def system_group():
    """Logbook system commands."""
    pass


@system_group.command("list")
def system_list():
    """List available logbook systems."""
    cmd_list_systems()


# -- template --

@cli.group("template")
def template_group():
    """Logbook template commands."""
    pass


@template_group.command("list")
def template_list():
    """List available logbook templates."""
    cmd_list_templates()


# -- config --

@cli.group("config")
def config_group():
    """Configuration commands."""
    pass


@config_group.command("show")
def config_show():
    """Show current configuration."""
    cmd_show_config()


@config_group.command("edit")
def config_edit():
    """Open the settings file in your editor."""
    cmd_edit_config()



if __name__ == "__main__":
    cli()
