LOCK TABLES `item_item_project` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `item_item_project` DISABLE KEYS */;
/*!40000 ALTER TABLE `item_item_project` ENABLE KEYS */;
UNLOCK TABLES;
