LOCK TABLES `property_metadata` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `property_metadata` DISABLE KEYS */;
/*!40000 ALTER TABLE `property_metadata` ENABLE KEYS */;
UNLOCK TABLES;
