LOCK TABLES `item_item_category` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `item_item_category` DISABLE KEYS */;
/*!40000 ALTER TABLE `item_item_category` ENABLE KEYS */;
UNLOCK TABLES;
